{{- if .Values.Nashm.configYamlContent }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "Nashm.fullname" $ }}-config
data:
  Nashm.yaml: |
{{ .Values.Nashm.configYamlContent | indent 4 }}

{{- end }}